num = int(input('Digite um número para demonstrar sua tabuada: '))
#t1 = (num * 1)
#t2 = (num * 2)
#t3 = (num * 3)
#t4 = (num * 4)
#t5 = (num * 5)
#t6 = (num * 6)
#t7 = (num * 7)
#t8 = (num * 8)
#t9 = (num * 9)
#t10 = (num * 10)

#print('A tabuada do seu número é: \n x 1 = {} \n x 2 = {} \n x 3 = {} \n x 4 = {} \n x 5 = {} \n x 6 = {} \n x 7 = {} \n x 8 = {} \n x 9 = {} \n x 10 = {}'.format(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10 ))
print('-' * 12)
print('{} x {:2} = {} '.format(num, 1, num *1))
print('{} x {:2} = {} '.format(num, 2, num *2))
print('{} x {:2} = {} '.format(num, 3, num *3))
print('{} x {:2} = {} '.format(num, 4, num *4))
print('{} x {:2} = {} '.format(num, 5, num *5))
print('{} x {:2} = {} '.format(num, 6, num *6))
print('{} x {:2} = {} '.format(num, 7, num *7))
print('{} x {:2} = {} '.format(num, 8, num *8))
print('{} x {:2} = {} '.format(num, 9, num *9))
print('{} x {:2} = {}'.format(num, 10, num *10))